using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public interface ICommand
{
    // Different types of Comands are generated by players.
    long id { get; set; }

    /// <summary>
    /// used by CommandCommander to run commands. returning true will conclude the command and remove
    /// it from execution.
    /// </summary>
    /// <returns></returns>
    bool Execute();

    /// <summary>
    /// Adds command to the list of commands to be persisted into a replay file.
    /// </summary>
    void Record();
}
