using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public interface ICommand
{
    // Different types of Comands are generated by players.
    long id { get; set; }

    // Selection
    // 
    bool Execute();

    void Record();
}
