using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public interface ICommand
{
    // Different types of Comands are generated by players.

    // Selection
    // 

    // bool Execute();

    void Record();
}
